language: java
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
jdk: openjdk11
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  app: jader-app
  api_key:
    secure: OxJbXVH7YRfOtrCf+vQ2uXBTkC4kUz/xatc1FuPAGmQEXfGCQcskDj+ikNVujcqHt4OBhn8pHJRvhe0mWqcfhPHfdw9g54GRkX14mfLYPcvPKFPdt3arZZ7W2eI24kTmZUjCGO2IKv8pPX67Ziy8B2foFwXcNcnv1acOT63eevKZ7QZwAHDLxnj3wM48QiHpbd+4oxe9xa3kY1Wy0d9EctVMMU0lHdqIZZi4MkhMWomsLtqApyug2v27OfOwmP9eRk66MTJlXJsVyDkDEXnh8/U4q/fGIqOKSoHf0DymUndNchrHL96WJwbkJU7aLsu+zu4H0OH1rC6jf81RXU4gjqhv9j4ca8hEa8mnmh65O3XngfgGMhvqW8PjfQG8S7/pfVAa9LaKD4oLERb5NFURQp0Obb0rlhr52I70NOxh1LxtHK0rJnuMsYk+XMDT5juM1cVsyxR1dXSwBQqGuo8fH6XPV3MAlPd0ZN8Vi6NwysFf/BkQx7bqwRWaGYL0OAsEHWTKdXqzRkmTZi+5iXU7mhFQpFIaY9XYR9eDxjrqb7PwZN0E5Wym0Tz9kCP0GkEIUsROBRF72OCCRf9QygwsUKndy9YHMP40qJxSRfr9RvmdUMWTbsXEzUo+Cu/zJXNGLIVrNOet8cd+w62ypUGCTFb6hslSYmEjl14HthDMVWs=
